// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJxc5MhQxDo9M6d7PT6n_zT4YMUy8RjCU',
    appId: '1:929978054372:web:db7670c19d2ab9f3f21ef1',
    messagingSenderId: '929978054372',
    projectId: 'todoappid',
    authDomain: 'todoappid.firebaseapp.com',
    storageBucket: 'todoappid.appspot.com',
    measurementId: 'G-1QVV1NWG89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa0IKCGtMEZ_HAWFNVhFeqgUsGjFTmIyg',
    appId: '1:929978054372:android:2494448d6be5821ff21ef1',
    messagingSenderId: '929978054372',
    projectId: 'todoappid',
    storageBucket: 'todoappid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSEdI785X2-nNBz9FsC3xse8xwwKaL76g',
    appId: '1:929978054372:ios:a206d7bd88f08c6cf21ef1',
    messagingSenderId: '929978054372',
    projectId: 'todoappid',
    storageBucket: 'todoappid.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSEdI785X2-nNBz9FsC3xse8xwwKaL76g',
    appId: '1:929978054372:ios:a206d7bd88f08c6cf21ef1',
    messagingSenderId: '929978054372',
    projectId: 'todoappid',
    storageBucket: 'todoappid.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJxc5MhQxDo9M6d7PT6n_zT4YMUy8RjCU',
    appId: '1:929978054372:web:6f646ffbb04bb69bf21ef1',
    messagingSenderId: '929978054372',
    projectId: 'todoappid',
    authDomain: 'todoappid.firebaseapp.com',
    storageBucket: 'todoappid.appspot.com',
    measurementId: 'G-ZK28X5913X',
  );
}
